project_id = "psryfvfdmjguhamvmqqd"

[functions.create-user]
verify_jwt = true

[functions.seed-demo-data]
verify_jwt = true

[functions.clear-demo-data]
verify_jwt = true

[functions.fetch-monthly-power-bills]
verify_jwt = false

[functions.capture-bill-receipt]
verify_jwt = false

[functions.send-power-bill-reminders]
verify_jwt = false