project_id = "psryfvfdmjguhamvmqqd"

[functions.fetch-monthly-power-bills]
verify_jwt = false

[functions.capture-bill-receipt]
verify_jwt = false

[functions.send-power-bill-reminders]
verify_jwt = false